=== elemonnier/A1_HTML_CSS/TP4_XML/school.dtd
<!ELEMENT school (institution, school-site, admission-type, degree)>

        <!ELEMENT institution (name, group, sites, admission-types, degrees)>
        <!ELEMENT school-site (name)>
                <!ATTLIST school-site id ID #REQUIRED>
        <!ELEMENT admission-type (name, via, description, types)>
                <!ATTLIST admission-type id ID #REQUIRED>
        <!ELEMENT admission-types (#PCDATA)>
        <!ELEMENT sites (school-site)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT group (#PCDATA)>
        <!ELEMENT via (#PCDATA)>
        <!ELEMENT degrees (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT types (type)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT degree (name, admissions)>
                <!ATTLIST degree type CDATA #REQUIRED>
                <!ATTLIST degree domain CDATA #REQUIRED>
        <!ELEMENT admissions (admission)>
        <!ELEMENT admission (method, name, shortname, availability)>
        <!ELEMENT availability (site)>
        <!ELEMENT shortname (#PCDATA)>
        <!ELEMENT site (#PCDATA)>
                <!ATTLIST admission from CDATA #REQUIRED>
                <!ATTLIST admission type CDATA #REQUIRED>
                <!ATTLIST method type CDATA #REQUIRED>

=== elemonnier/A1_HTML_CSS/TP4_XML/school.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE school SYSTEM "school.dtd">
<school>
        <institution>
                <name>ISEN Ouest</name>
                <group>Yncréa Ouest</group>
                <sites/><!-- On remplira plus tard -->
                <admission-types/><!-- On remplira plus tard -->
                <degrees/><!-- On remplira plus tard -->
        </institution>
        <school-site id="Brest">
                <name>Brest</name>
        </school-site>
        <school-site id="Rennes">
                <name>Rennes</name>
        </school-site>
        <school-site id="Nantes">
                <name>Nantes</name>
        </school-site>
        <admission-type id="puissance-alpha">
                <name>Concours Puissance Alpha</name>
                <via>Parcours Sup</via>
                <description>...</description>
                <types>
                        <type>initial</type>
                </types>
        </admission-type>
        <admission-type id="fesic-prepa">
                <name>Concours FESIC Prépa</name>
                <description>...</description>
                <types>
                        <type>initial</type>
                </types>
        <admission-type id="interview">
                <name>Etude de dossier &amp; Entretien</name>
                <description>...</description>
                <types>
                        <type>initial</type>
                        <type>alternance</type>
                </types>
        </admission-type>
        <degree type="master" domain="engineering">
                <name>Ingénieur ISEN Yncréa Ouest</name>
                <admissions>
                        <admission from="bac" type="initiale">
                                <method type="puissance-alpha"/>
                                <name>Cycle Informatique &amp; Réseaux</name>
                                <shortname>CIR</shortname>
                                <availability>
                                        <site>Brest</site>
                                        <site>Rennes</site>
                                        <site>Nantes</site>
                                </availability>
                        </admission>
                        <admission from="bac" type="initiale">
                                <method type="puissance-alpha"/>
                                <name>Cycle Généraliste des Sciences de l'Ingénieur</name>
                                <shortname>CGSI</shortname>
                                <availability>
                                        <site>Brest</site>
                                        <site>Nantes</site>
                                </availability>
                        </admission>
                        <admission from="bac" type="initiale">
                                <method type="puissance-alpha"/>
                                <name>Cycle Biologie &amp; Sciences et Techniques</name>
                                <shortname>BIOST</shortname>
                                <availability>
                                        <site>Brest</site>
                                </availability>
                        </admission>
                        <admission from="bac" type="initiale">
                                <method type="puissance-alpha"/>
                                <name>Cycle Economie, Numérique et Technologies</name>
                                <shortname>CENT</shortname>
                                <availability>
                                        <site>Brest</site>
                                </availability>
                        </admission>
                        <admission from="bac+2" type="initiale">
                                <method type="fesic-prepa"/>
                                <name>Cycle Généraliste des Sciences de l'Ingénieur</name>
                                <shortname>CGSI</shortname>
                                <availability>
                                        <site>Brest</site>
                                </availability>
                        </admission>
                        <admission from="bac+2" type="alternance">
                                <method type="interview"/>
                                <name>Cycle Ingénieur Par Apprentissage</name>
                                <shortname>CIPA</shortname>
                                <availability>
                                        <site>Brest</site>
                                </availability>
                        </admission>
                </admissions>
        </degree>
</school>
